### ISSUE TITLE
Email Templating

### ISSUE THREAD

**Issue by alexlai18** [devsoc-unsw/chaos#517]
Implement the ability for organisations to have their own Email Templates, with adjustable variables to send to the applicants.

This ticket will involve:
- CRUD operations on the backend
- Frontend utility function to convert textbox input into HTML text

**Comment by KavikaPalletenne** [comment]
Store email templates (strings) in DB, with a relation to an organisation.

i.e. schema will look something like:
```sql
CREATE TABLE email_templates (
    id BIGINT PRIMARY KEY,
    organisation_id BIGINT NOT NULL,
    template_name TEXT NOT NULL,
    template TEXT NOT NULL
)
```
